apiVersion: v1
kind: Pod
metadata:
  namespace: default
  labels:
    jenkins: agent
spec:
  containers:
    - name: docker
      image: docker:dind
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
