apiVersion: v1
kind: Pod
metadata:
  namespace: default
  labels:
    jenkins: agent
spec:
  containers:
    - name: docker
      image: docker:dind
      securityContext:
        privileged: true
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true
